# Generated by Django 4.2.21 on 2025-05-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(default='DOCENTE', max_length=20),
        ),
    ]
