# Generated by Django 5.2.1 on 2025-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30)),
                ('subjectDescription', models.CharField(max_length=100)),
                ('subjectCredits', models.PositiveSmallIntegerField()),
                ('subjectSemester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compDescription', models.CharField(max_length=255)),
                ('compLevel', models.CharField(max_length=50)),
            ],
        ),
    ]
