# Generated by Django 5.2.1 on 2025-06-04 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critPonderacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perSemester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proCompDescription', models.CharField(max_length=255)),
                ('proCompLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30)),
                ('subjectDescription', models.CharField(max_length=100)),
                ('subjectCredits', models.PositiveSmallIntegerField()),
                ('subjectSemester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teaType', models.CharField(max_length=50)),
                ('teaTypeId', models.CharField(max_length=50)),
                ('teaRecentTitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivCategoria', models.CharField(max_length=30)),
                ('nivDescripcion', models.CharField(max_length=100)),
                ('EvaluationCriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.evaluationcriteria')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proRADescription', models.CharField(max_length=255)),
                ('programCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.programcompetence')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='Rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.rubric'),
        ),
        migrations.CreateModel(
            name='CompetenceProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.programcompetence')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compDescription', models.CharField(max_length=255)),
                ('compLevel', models.CharField(max_length=50)),
                ('programCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.programcompetence')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raDescription', models.CharField(max_length=255)),
                ('subjectCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectcompetence')),
            ],
        ),
        migrations.AddField(
            model_name='rubric',
            name='SubjectRA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectra'),
        ),
        migrations.CreateModel(
            name='SubjectTeacherPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='subjectcompetence',
            name='subjectTeacherPeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectteacherperiod'),
        ),
    ]
