# Generated by Django 5.2.1 on 2025-06-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacherperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.period'),
        ),
        migrations.AlterField(
            model_name='subjectteacherperiod',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.subject'),
        ),
        migrations.AlterField(
            model_name='subjectteacherperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_periods', to='AcademApi.teacher'),
        ),
    ]
