# Generated by Django 5.2.1 on 2025-05-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perSemester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaMail', models.EmailField(max_length=254, unique=True)),
                ('teaName', models.CharField(max_length=100)),
                ('teaLastName', models.CharField(max_length=100)),
                ('teaType', models.CharField(max_length=50)),
                ('teaTypeId', models.CharField(max_length=50, unique=True)),
                ('teaRecentTitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.programcompetence')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacherPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='subjectcompetence',
            name='subjectTeacherPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectteacherperiod'),
            preserve_default=False,
        ),
    ]
