# Generated by Django 5.2.1 on 2025-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademApi', '0002_period_teacher_competenceprogramsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaTypeId',
            field=models.CharField(max_length=50),
        ),
    ]
