# Generated by Django 4.2.21 on 2025-05-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=30)),
                ('subjectDescription', models.CharField(max_length=100)),
                ('subjectCredits', models.PositiveSmallIntegerField()),
                ('subjectSemester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compDescription', models.CharField(max_length=255)),
                ('compLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raDescription', models.CharField(max_length=255)),
                ('subjectCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectcompetence')),
            ],
        ),
    ]
