# Generated by Django 5.2.1 on 2025-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compDescription', models.CharField(max_length=255)),
                ('compLevel', models.CharField(max_length=50)),
            ],
        ),
    ]
