# Generated by Django 5.2.1 on 2025-05-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raDescription', models.CharField(max_length=255)),
                ('subjectCompetence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademApi.subjectcompetence')),
            ],
        ),
    ]
